config/routes.rb
Rails.application.routes.draw do
  get 'search/index'

  get 'search/events'
  get 'search/import'

  root to: 'pages#home'

  get "recherche", to: "pages#recherche"

  resources :sports do
  end

  resources :trials do
  end
  resources :events do
  end
  resources :master_events do
  end

end

app/models/event.rb
require 'elasticsearch/model'

class Event < ActiveRecord::Base
	belongs_to :trial
	belongs_to :master_event
	include Elasticsearch::Model
	include Elasticsearch::Model::Callbacks

	def as_indexed_json(options = {})
	    as_json(:methods   => [ :search_keywords],
    				include: { trial: {include: { sport: {}}},
    						   master_event: {include: { organizer: {}}},
             })
	end

	def appendToKeyword(esKeywords, keyword)
		if keyword.to_s.empty?
			return esKeywords
		end
		return esKeywords.concat(keyword).concat(" ")
	end

	def search_keywords
		esKeywords = ""
		esKeywords = self.appendToKeyword(esKeywords, self.name)
		esKeywords = self.appendToKeyword(esKeywords, self.description)
		esKeywords = self.appendToKeyword(esKeywords, self.location)
		esKeywords = self.appendToKeyword(esKeywords, self.keywords)
		esKeywords = self.appendToKeyword(esKeywords, self.master_event.organizer.name)
		esKeywords = self.appendToKeyword(esKeywords, self.master_event.name)
		esKeywords = self.appendToKeyword(esKeywords, self.master_event.keywords)
		esKeywords = self.appendToKeyword(esKeywords, self.master_event.country)
		esKeywords = self.appendToKeyword(esKeywords, self.master_event.location)
		esKeywords = self.appendToKeyword(esKeywords, self.trial.name)
		esKeywords = self.appendToKeyword(esKeywords, self.trial.keywords)
		esKeywords = self.appendToKeyword(esKeywords, self.trial.description)
		esKeywords = self.appendToKeyword(esKeywords, self.trial.totalDistance.to_s)
		esKeywords = self.appendToKeyword(esKeywords, self.trial.sport.name)
		esKeywords = self.appendToKeyword(esKeywords, self.trial.sport.keywords)
		esKeywords = self.appendToKeyword(esKeywords, self.trial.sport.description)
        return esKeywords
    end

    def self.importIndex
		# Delete the previous articles index in Elasticsearch
		Event.__elasticsearch__.client.indices.delete index: Event.index_name rescue nil

		# Create the new index with the new mapping
		Event.__elasticsearch__.client.indices.create \
		  index: Event.index_name,
		  body: { settings: Event.settings.to_hash, mappings: Event.mappings.to_hash }

		Event.__elasticsearch__.refresh_index!

		Event.import
	end

end

app/models/master_event.rb
class MasterEvent < ActiveRecord::Base
  belongs_to :organizer
end

app/models/organizer.rb
class Organizer < ActiveRecord::Base
end

app/models/sport.rb
class Sport < ActiveRecord::Base
end

app/models/trial.rb
class Trial < ActiveRecord::Base
  belongs_to :sport
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :set_event, only: [ :show]

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)

    @event.save
    @events = Sport.all
    render :index

  end

  def index
    @events = Event.all

  end

  def show
  end

  private

  def set_event
    if Event.all.exists?
    @event = Event.find(params[:id])
    else
    @event = "no event available"
    end
  end

  def event_params
    params.require(:event).permit(:name, :description, :startDate, :endDate, :location, :capacity, :trial_id, :master_event_id)
  end


end

app/controllers/master_events_controller.rb
class MasterEventsController < ApplicationController
  before_action :set_master_event, only: [ :show]


  def show
    @events = Event.where(master_event_id: @master_event)

  end

  private


  def set_master_event
    @master_event = MasterEvent.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def recherche

    @sports = Sport.all
    @trials = Trial.all
    @master_events = MasterEvent.all
  end


    private

end

app/controllers/search_controller.rb
require 'json'

class SearchController < ApplicationController
  def index
  	if params[:q].present?
      # response = Event.search params[:q]
      response = SearchEventService.magicSearchHTML params[:q]
      render json: response
    else
    end
  end

  def events
    @events = Event.all
    searchEvents = []
    @events.each do |event|
    	eventHash = event.attributes
    	eventHash['title'] = event.name
    	eventHash['start'] = event.startDate
    	eventHash['logo'] = ActionController::Base.helpers.image_tag("#{event.trial.sport_id}/logo.png", size: "14")
    	searchEvents.push(eventHash)
    end
    render json: searchEvents
  end

  def import
    Event.importIndex
    render json: Hash.new
  end
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController

  before_action :set_sport, only: [ :show]

  def new
    @sport = Sport.new
  end

  def create
    @sport = Sport.new(sport_params)

    @sport.save
    @sports = Sport.all
    render :index

  end

  def index
    @sports = Sport.all

  end

  def show
    @trials = Trial.where(sport_id: @sport)
  end

  private

  def sport_params
    params.require(:sport).permit(:name, :description)
  end

  def set_sport
    if Sport.all.exists?
    @sport = Sport.find(params[:id])
    else
    @sport = "no sport available"
    end
  end

end

app/controllers/trials_controller.rb
class TrialsController < ApplicationController
  before_action :set_trial, only: [ :show]

  def new
    @trial = Trial.new
  end

  def create
    @trial = Trial.new(trial_params)

    @trial.save
    @trials = Trial.all
    render :index

  end

  def index
    @trials = Trial.all

  end

  def show
    @events = Event.where(trial_id: @trial)

  end

  private

  def trial_params
    params.require(:trial).permit(:name, :description)
  end

  def set_trial
    @trial = Trial.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/date_helper.rb
module DateHelper
	MONTH_REGEX = /.*(janvier|fevrier|mars|avril|mai|juin|juillet|aout|septembre|octobre|novembre|decembre).*/

	def self.extractMonth(query)
		if !query.scan(MONTH_REGEX).last.nil?
			return query.scan(MONTH_REGEX).last.first
		end
		return nil
	end

	def self.extractRange(query)
		month = self.extractMonth(query).to_s
		Rails.logger.debug "DateHelper > " + month
		return self.getMonthRanges(month)
	end

	def self.getMonthRanges(month)
		range = Hash.new
		if month == "janvier"
			range["gte"] = "2017-01-01"
			range["lte"] = "2017-01-31"
		elsif month =="fevrier"
			range["gte"] = "2017-02-01"
			range["lte"] = "2017-02-30"
		elsif month =="mars"
			range["gte"] = "2017-03-01"
			range["lte"] = "2017-03-31"
		elsif month =="avril"
			range["gte"] = "2017-04-01"
			range["lte"] = "2017-04-30"
		elsif month =="mai"
			range["gte"] = "2017-05-01"
			range["lte"] = "2017-05-31"
		elsif month =="juin"
			range["gte"] = "2017-06-01"
			range["lte"] = "2017-06-30"
		elsif month =="juillet"
			range["gte"] = "2017-07-01"
			range["lte"] = "2017-07-31"
		elsif month =="aout"
			range["gte"] = "2017-08-01"
			range["lte"] = "2017-08-31"
		elsif month =="septembre"
			range["gte"] = "2017-09-01"
			range["lte"] = "2017-09-30"
		elsif month =="octobre"
			range["gte"] = "2017-10-01"
			range["lte"] = "2017-10-31"
		elsif month =="novembre"
			range["gte"] = "2017-11-01"
			range["lte"] = "2017-11-30"
		elsif month =="decembre"
			range["gte"] = "2017-12-01"
			range["lte"] = "2017-12-31"
		else
			return nil
		end
		return range
	end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/master_events_helper.rb
module MasterEventsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sports_helper.rb
module SportsHelper
	def self.extractSport(query)
		@sports = Sport.select(:name).distinct
		@sports.each do |sport|
			if query.downcase.include? sport.name.downcase
				return sport.name.downcase
			end
		end
		return nil
	end
end

app/helpers/trials_helper.rb
module TrialsHelper
end

app/views/events/index.html.erb
<div class="container">
  <div class="row text-center">
    <h1>Evénements</h1>
    <% @events.each do |event| %>
      <p> <%= event.name %> </p>
    <%end%>
  </div>
</div>

app/views/events/new.html.erb
<div class="container">
<div class="row text-center">
<%= form_for(@event) do |f| %>
  <%= f.label :nom %>:
  <%= f.text_field :name %><br />
  <%= f.label :description %>:
  <%= f.text_field :description %><br />
  <%= f.label :Début %>:
  <%= f.text_field :startDate %><br />
  <%= f.label :Fin %>:
  <%= f.text_field :endDate %><br />
  <%= f.label :Lieu %>:
  <%= f.text_field :location %><br />
  <%= f.label :Capacité %>:
  <%= f.text_field :capacity %><br />
  <%= f.label :Epreuve %>:
  <%= f.text_field :trial_id %><br />
  <%= f.label :MasterEvent %>:
  <%= f.text_field :master_event_id %><br />
<%= f.submit %>
<% end %>
</div>
</div>

app/views/events/search_list.html.erb
<div class="row results-container">
	<% if type == "date" or type == "sport-date" %>
		<% if type == "sport-date"%>
			Vous chercher un évènement de <%= sport %> pour le mois de <%= month %>
	    <% elsif type == "date"%>
			Vous chercher un évènement pour le mois de <%= month %>
	    <% end %>

		<table class="table table-striped results-table">
			<thead>
				<tr>
					<th>Date</th>
					<th>Épreuve</th>
					<th>Évènement</th>
					<th>Distance</th>
					<th>Lieu</th>
				</tr>
			</thead>
			<tbody>
    			<% data.each do |event| %>
					<tr>
						<td><%= event["date"] %></td>
						<td><%= event["name"] %></td>
						<td><a href="<%= event["link"] %>"><%= event["master_event_name"] %></a></td>
						<td><%= event["distance"] %></td>
						<td><%= event["location"] %></td>
					</tr>
    			<%end%>
			</tbody>
		</table>
	<% else %>
	    <% if type == "sport"%>
			Vous chercher un évènement de <%= sport %>
	    <% end %>
	    <% data.each do |month, events| %>
			<h3 class="results-month"><%= month %></h3>
			<table class="table table-striped results-table">
				<thead>
					<tr>
						<th>Date</th>
						<th>Épreuve</th>
						<th>Évènement</th>
						<th>Distance</th>
						<th>Lieu</th>
					</tr>
				</thead>
				<tbody>
	    			<% events.each do |event| %>
						<tr>
							<td><%= event["date"] %></td>
							<td><%= event["name"] %></td>
							<td><a href="<%= event["link"] %>"><%= event["master_event_name"] %></a></td>
							<td><%= event["distance"] %></td>
							<td><%= event["location"] %></td>
						</tr>
	    			<%end%>
				</tbody>
			</table>
	    <%end%>
	<% end %>
</div>

app/views/events/show.html.erb
<div class="container">
  <div class="row text-center">
    <h1>Mon Evénement</h1>
    <p> <%=@event%> </p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>SPORTIFY</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/master_events/show.html.erb
<div class="container">
  <div class="row text-center">
    <h4>Evénement / Compétition</h4>
    <h2> <%=@master_event.name%> </h2>
    <p> <%=@master_event.startDate%></p>
    <p>Sport : <%=@events.first.trial.sport.name %></p>
  </div>
  <div class="row">
    <h4>Les épreuves</h4>
    <% @events.each do |event| %>
    <p><%= event.trial.name %> </p>
    <%end%>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner">
  <div class="banner-content">
    <%= image_tag("logo_w.png", :class=>"home-logo") %>
    <p>Le plus grand terrain de sport</p>
    <div class="container">
      <div class="row">
        <%= form_tag("/search/index", method: "get", class: "index-search", autocomplete: "off") do %>
          <div class="xs-10">
            <%= text_field_tag(:q, "", class: 'form-control', placeholder: "Quel est ton prochain défi ?") %>
          </div>
          <p></p>
          <div class="xs-2">
            <%= submit_tag("Chercher", :id=>"button", :class=>"btn btn-primary", :name=>"submit") %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row results-container">
    <table class="table table-striped results-table">
    </table>
  </div>
</div>

app/views/pages/recherche.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,36,61,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://static.pexels.com/photos/8983/pexels-photo.jpeg');">
  <div class="banner-content">

  <div class="container">
    <div class="row text-center">
      <h4>Recherche détaillée</h4>
    <%= form_tag "/pages/recherche" do %>
    <%= label_tag 'Sport : ' %>
    <%= select_tag "sport", options_from_collection_for_select(@sports, "id", "name") %> </br>

    <%= label_tag 'Epreuve : ' %>
    <%= select_tag "epreuve", options_from_collection_for_select(@trials, "id", "name") %> </br>
    <%= label_tag 'Dans un rayon de : ' %></br>

  <input id="slider1" type="text" data-slider-ticks="[0, 25, 50, 100, 200]" data-slider-ticks-snap-bounds="30" data-slider-ticks-labels='["0", "25", "50", "100", "200"]'/> </br>
    <%= label_tag 'Autour de : ' %></br>

    <%= text_field_tag "account", "Ville" %> </br>

    <%= label_tag 'Période : ' %></br>



  <p>Distance souhaitée :</p>  <b>1 km  </b> <input id="slider2" type="text" class="span2" value="" data-slider-min="0" data-slider-max="200" data-slider-step="5" data-slider-value="[10,150]" data-slider-ticks="[10, 21, 42, 100]"/> <b>  200 km</br>



    <%= submit_tag "Recherche" %></br>
    <% end %>

    </div>
  </div>

  <div class="container">
    <div class="row text-center">
    <!-- L'idée est de mettre de l'ajax pour que le compteur s'update a chaque modification de la form -->
    <p># événements à venir : </p> </br>
    <p> <%= @master_events.length %> </p>
    </div>
  </div>

  </div>
</div>

app/views/search/events.html.erb
<%= @events.to_json %>

app/views/search/index.html.erb
<div class="container">
<div class="row text-center">
	<%= form_tag("/search/index", method: "get", class: "event-search") do %>
	  <%= label_tag(:q, "Search for:") %>
	  <%= text_field_tag(:q) %>
	  <%= submit_tag("Search") %>
	<% end %>
</div>
<div class="calendar"></div>
</div>

app/views/sports/index.html.erb
<div class="container sports-container">
  <div class="row text-center">
    <h1>Sports</h1>
    <% @sports.each do |sport| %>
	    <div class="item">
          <%= link_to image_tag("#{sport.id}/logo.png"), sport_path(sport) %>
      	</div>
    <%end%>
  </div>
</div>

app/views/sports/new.html.erb
<div class="container">
<div class="row text-center">
<%= form_for(@sport) do |f| %>
  <%= f.text_field :name %>
  <%= f.text_field :description %>
  <%= f.submit %>

<% end %>
</div>
</div>

app/views/sports/show.html.erb
<div class="text-center sport-header" style="background-image: linear-gradient(-225deg, rgba(0,36,61,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= asset_path "#{@sport.id}/banner.jpg" %>')">
  <div class="sport-title">
    <h1> <%=@sport.name%> </h1>
    <h3> <%=@sport.description%></h3>
  </div>
</div>
<div class="container">
  <div class="row">
    <h4>Epreuves</h4>
    <% @trials.each do |trial| %>
    <%= link_to trial.name, trial_path(trial), {class: "btn btn-primary"} %>
    <%end%>
  </div>
</div>

app/views/trials/show.html.erb
<div class="container">
  <div class="row text-center">
    <h4>Epreuve</h4>
    <h2> <%=@trial.name%> </h2>
    <p> <%=@trial.description%></p>
  </div>
  <div class="row">
    <h4>Les événements</h4>
    <% @events.each do |event| %>
    <%= link_to event.master_event.name, master_event_path(event.master_event), {class: "btn btn-primary"} %>
    <%end%>


  </div>
</div>